version: '3'

services:
  perf-grafana:
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    container_name: perf-grafana
    hostname: perf-grafana
    networks:
      perf-network:
        aliases:
            - perf-grafana
            
  perf-influxdb:
    image: influxdb:1.7.3
    ports:
      - "8086:8086"
      - "2003:2003"
    container_name: perf-influxdb
    hostname: perf-influxdb
    networks:
      perf-network:
        aliases:
            - perf-influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb

networks:
  perf-network:
    driver: "bridge"

